version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    container_name: devminelab-mongo
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGODB_INITDB_ROOT_USERNAME: devminelab-app
      MONGODB_INITDB_ROOT_PASSWORD: Uqis1cetaAeHIAMA
      MONGODB_INITDB_DATABASE: devminelab-db
      MONGODB_ENABLE_NUMACTL: "true"
    command: ["mongod", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local 